repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: '^(docs/sphinx_setup/_build|docs/_build|benchmarks/results|probe_(src|tgt)\.json)'
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
        exclude: '^(docs/sphinx_setup/_build|docs/_build|benchmarks/results|probe_(src|tgt)\.json)'
      - id: check-yaml
        exclude: '^(docs/sphinx_setup/_build|docs/_build|benchmarks/results)'
      - id: check-json
        exclude: '^(docs/sphinx_setup/_build|docs/_build|benchmarks/results)'
      - id: check-added-large-files
        exclude: '^(docs/sphinx_setup/_build|docs/_build|benchmarks/results)'
